### ISSUE TITLE
RuntimeError: CUDA error: invalid argument in inference.

### ISSUE THREAD

**Issue by jkowaur** [bytedance/pv3d#6]
I try to run the below command to inference result, but get CUDA error. 

command: 
python3 gen_video.py \
config=configs/projects/pv3d.yaml \
run_type=val model=pv3d dataset=voxceleb \
env.save_dir=save/ \
training.num_workers=2 \
training.rendering_resolution=128 \
checkpoint.resume_file=cache/vc_video_reg_06_vid_065_gamma_2_dual_layer_4_res64_reproduce.ckpt \
dataset_config.voxceleb.data_dir=cache/voxceleb

error:
Traceback (most recent call last):
  File "gen_video.py", line 119, in <module>
    run()
  File "gen_video.py", line 115, in run
    main(configuration, predict=predict)
  File "gen_video.py", line 61, in main
    trainer.generating()
  File "/data3/backup/pv3d/lib/trainers/trainer.py", line 170, in generating
    self.generating_loop(dataset)
  File "/data3/backup/pv3d/lib/trainers/core/evaluation_loop.py", line 348, in generating_loop
    output = generator.synthesis(bws, bz_motion, bTs, bc, neural_rendering_resolution=config.training.rendering_resolution, noise_mode='const', return_depth=True)
  File "/data3/backup/pv3d/lib/models/videg3d/networks/triplane.py", line 85, in synthesis
    feature_samples, depth_samples, weights_samples, depth, weight_total = self.renderer(planes, self.decoder, ray_origins, ray_directions, self.rendering_kwargs, return_depth=return_depth) # channels last
  File "/home/jerry/anaconda3/envs/pv3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data3/backup/pv3d/lib/models/videg3d/networks/volumetric_rendering/renderer.py", line 119, in forward
    out = self.run_model(planes, decoder, sample_coordinates, sample_directions, rendering_options)
  File "/data3/backup/pv3d/lib/models/videg3d/networks/volumetric_rendering/renderer.py", line 155, in run_model
    sampled_features = sample_from_planes(self.plane_axes, planes, sample_coordinates, padding_mode='zeros', box_warp=options['box_warp'])
  File "/data3/backup/pv3d/lib/models/videg3d/networks/volumetric_rendering/renderer.py", line 71, in sample_from_planes
    projected_coordinates = project_onto_planes(plane_axes, coordinates).unsqueeze(1)
  File "/data3/backup/pv3d/lib/models/videg3d/networks/volumetric_rendering/renderer.py", line 57, in project_onto_planes
    inv_planes = torch.linalg.inv(planes).unsqueeze(0).expand(N, -1, -1, -1).reshape(N*n_planes, 3, 3)
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

What's wrong with the command?

Thanks~

**Comment by zcxu-eric** [comment]
Hi, thanks for your interest in our work.

I used the same command on my side but cannot reproduce this error, could you please check the intallation of CUDA or simply use a different machine?

The command looks good but the pretrained checkpoint used here is ```res64```, so it is recommaned to use a ```training.rendering_resolution=64```.
